# Generated by Django 3.2.22 on 2023-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231119_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('commenter_name', models.CharField(max_length=200)),
                ('commenter_body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
